kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: control-plane-operator
rules:
- apiGroups:
  - control-plane.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-control-plane-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: control-plane-operator
  apiGroup: rbac.authorization.k8s.io
